In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import pandas as pd
import sys

In [3]:
sys.path.insert(0, '/usr/src/volume/volume/scripts')

In [4]:
from qty_checker import QtyChecker
from etl import ETL

/opt/conda/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [5]:
qc_train = QtyChecker('/usr/src/volume/volume/datasets/train.csv', 'train_report')

In [6]:
pr, df = qc_train.do()

Summarize dataset: 100%|██████████| 87/87 [00:00<00:00, 218.45it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:07<00:00,  7.40s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  1.63it/s]
/opt/conda/lib/python3.9/site-packages/pandas_profiling/profile_report.py:262: UserWarning: Extension  not supported. For now we assume .html was intended. To remove this warning, please use .html or .json.
  warnings.warn(
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 17.22it/s]

In [7]:
pd.set_option('display.max_rows', 500)

In [8]:
etl = ETL('train.csv')
df_etl = etl.run()

In [9]:
df_etl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1451 entries, 0 to 1450
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   index          1451 non-null   int64
 1   Id             1451 non-null   int64
 2   MSSubClass     1451 non-null   int64
 3   MSZoning       1451 non-null   int64
 4   LotArea        1451 non-null   int64
 5   Street         1451 non-null   int64
 6   Alley          1451 non-null   int64
 7   LotShape       1451 non-null   int64
 8   LandContour    1451 non-null   int64
 9   Utilities      1451 non-null   int64
 10  LotConfig      1451 non-null   int64
 11  LandSlope      1451 non-null   int64
 12  Neighborhood   1451 non-null   int64
 13  Condition1     1451 non-null   int64
 14  Condition2     1451 non-null   int64
 15  BldgType       1451 non-null   int64
 16  HouseStyle     1451 non-null   int64
 17  OverallQual    1451 non-null   int64
 18  OverallCond    1451 non-null   int64
 19  YearBuilt      1451 non-null   int64
 20  YearRemodAdd   1451 non-null   int64
 21  RoofStyle      1451 non-null   int64
 22  RoofMatl       1451 non-null   int64
 23  Exterior1st    1451 non-null   int64
 24  Exterior2nd    1451 non-null   int64
 25  MasVnrType     1451 non-null   int64
 26  MasVnrArea     1451 non-null   float64
 27  ExterQual      1451 non-null   int64
 28  ExterCond      1451 non-null   int64
 29  Foundation     1451 non-null   int64
 30  BsmtQual       1451 non-null   int64
 31  BsmtCond       1451 non-null   int64
 32  BsmtExposure   1451 non-null   int64
 33  BsmtFinType1   1451 non-null   int64
 34  BsmtFinSF1     1451 non-null   int64
 35  BsmtFinType2   1451 non-null   int64
 36  BsmtFinSF2     1451 non-null   int64
 37  BsmtUnfSF      1451 non-null   int64
 38  TotalBsmtSF    1451 non-null   int64
 39  Heating        1451 non-null   int64
 40  HeatingQC      1451 non-null   int64
 41  CentralAir     1451 non-null   object
 42  Electrical     1451 non-null   int64
 43  1stFlrSF       1451 non-null   int64
 44  2ndFlrSF       1451 non-null   int64
 45  LowQualFinSF   1451 non-null   int64
 46  GrLivArea      1451 non-null   int64
 47  BsmtFullBath   1451 non-null   int64
 48  BsmtHalfBath   1451 non-null   int64
 49  FullBath       1451 non-null   int64
 50  HalfBath       1451 non-null   int64
 51  BedroomAbvGr   1451 non-null   int64
 52  KitchenAbvGr   1451 non-null   int64
 53  KitchenQual    1451 non-null   int64
 54  TotRmsAbvGrd   1451 non-null   int64
 55  Functional     1451 non-null   int64
 56  Fireplaces     1451 non-null   int64
 57  FireplaceQu    1451 non-null   int64
 58  GarageType     1451 non-null   int64
 59  GarageYrBlt    1451 non-null   object
 60  GarageFinish   1451 non-null   int64
 61  GarageCars     1451 non-null   int64
 62  GarageArea     1451 non-null   int64
 63  GarageQual     1451 non-null   int64
 64  GarageCond     1451 non-null   int64
 65  PavedDrive     1451 non-null   object
 66  WoodDeckSF     1451 non-null   int64
 67  OpenPorchSF    1451 non-null   int64
 68  EnclosedPorch  1451 non-null   int64
 69  3SsnPorch      1451 non-null   int64
 70  ScreenPorch    1451 non-null   int64
 71  PoolArea       1451 non-null   int64
 72  PoolQC         1451 non-null   int64
 73  Fence          1451 non-null   int64
 74  MiscFeature    1451 non-null   int64
 75  MiscVal        1451 non-null   int64
 76  MoSold         1451 non-null   int64
 77  YrSold         1451 non-null   int64
 78  SaleType       1451 non-null   int64
 79  SaleCondition  1451 non-null   int64
 80  SalePrice      1451 non-null   int64
dtypes: float64(1), int64(77), object(3)
memory usage: 918.3+ KB

In [15]:
df_etl.isna().sum()

index            0
Id               0
MSSubClass       0
MSZoning         0
LotArea          0
Street           0
Alley            0
LotShape         0
LandContour      0
Utilities        0
LotConfig        0
LandSlope        0
Neighborhood     0
Condition1       0
Condition2       0
BldgType         0
HouseStyle       0
OverallQual      0
OverallCond      0
YearBuilt        0
YearRemodAdd     0
RoofStyle        0
RoofMatl         0
Exterior1st      0
Exterior2nd      0
MasVnrType       0
MasVnrArea       0
ExterQual        0
ExterCond        0
Foundation       0
BsmtQual         0
BsmtCond         0
BsmtExposure     0
BsmtFinType1     0
BsmtFinSF1       0
BsmtFinType2     0
BsmtFinSF2       0
BsmtUnfSF        0
TotalBsmtSF      0
Heating          0
HeatingQC        0
CentralAir       0
Electrical       0
1stFlrSF         0
2ndFlrSF         0
LowQualFinSF     0
GrLivArea        0
BsmtFullBath     0
BsmtHalfBath     0
FullBath         0
HalfBath         0
BedroomAbvGr     0
KitchenAbvGr     0
KitchenQual      0
TotRmsAbvGrd     0
Functional       0
Fireplaces       0
FireplaceQu      0
GarageType       0
GarageYrBlt      0
GarageFinish     0
GarageCars       0
GarageArea       0
GarageQual       0
GarageCond       0
PavedDrive       0
WoodDeckSF       0
OpenPorchSF      0
EnclosedPorch    0
3SsnPorch        0
ScreenPorch      0
PoolArea         0
PoolQC           0
Fence            0
MiscFeature      0
MiscVal          0
MoSold           0
YrSold           0
SaleType         0
SaleCondition    0
SalePrice        0
dtype: int64

In [16]:
df_etl

,index,Id,MSSubClass,MSZoning,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,0,1,60,0,8450,0,0,0,0,0,...,0,0,0,0,0,2,2008,0,0,208500
1,1,2,20,0,9600,0,0,0,0,0,...,0,0,0,0,0,5,2007,0,0,181500
2,2,3,60,0,11250,0,0,1,0,0,...,0,0,0,0,0,9,2008,0,0,223500
3,3,4,70,0,9550,0,0,1,0,0,...,0,0,0,0,0,2,2006,0,1,140000
4,4,5,60,0,14260,0,0,1,0,0,...,0,0,0,0,0,12,2008,0,0,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1446,1455,1456,60,0,7917,0,0,0,0,0,...,0,0,0,0,0,8,2007,0,0,175000
1447,1456,1457,20,0,13175,0,0,0,0,0,...,0,0,1,0,0,2,2010,0,0,210000
1448,1457,1458,70,0,9042,0,0,0,0,0,...,0,0,3,1,2500,5,2010,0,0,266500
1449,1458,1459,20,0,9717,0,0,0,0,0,...,0,0,0,0,0,4,2010,0,0,142125
1450,1459,1460,20,0,9937,0,0,0,0,0,...,0,0,0,0,0,6,2008,0,0,147500